export const SKILL_CATEGORIES = [
  "Web Development",
  "App Development",
  "Software Engineering",
  "UI/UX Design",
  "Graphic Design",
  "Video Editing",
  "Animation",
  "Content Writing",
  "Copywriting",
  "Translation",
  "Data Entry",
  "Data Analysis",
  "Digital Marketing",
  "SEO",
  "Social Media Management",
  "Photography",
  "Customer Support",
  "Virtual Assistant",
  "Accounting",
  "Legal Consulting",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Tutor",
  "Fitness Coaching",
];
